security:
  oauth2:
    client:
      clientId: 533938794033786
      clientSecret: d9666b104c71544142c6ddc602efbec6
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://graph.facebook.com/me